service:
  name: demo-serverless-lambda

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage}
  region: ap-southeast-1
  deploymentBucket:
    name: ${self:custom.deploy_bucket.${self:provider.stage}}
  environment:
    DOWNLOAD_URL: ${self:custom.download_url.${self:provider.stage}.url}
    DB_HOST: ${self:custom.source_db.${self:provider.stage}.host}
    DB_USER: ${self:custom.source_db.${self:provider.stage}.user}
    DB_P: ${self:custom.source_db.${self:provider.stage}.p}
    DB_NAME: ${self:custom.source_db.${self:provider.stage}.db}

package:
  exclude:
    - '**/*'
  individually: true

functions:
  load-tables:
    handler: load_tables.lambda_handler
    description: Loads O*NET data to MySql database
    memorySize: 1024
    timeout: 60
    tags:
      created_by: ryan
    package:
      exclude:
        - '**'
      include:
        - load_tables.py

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: true
  deploy_bucket:
    dev: demo-serverless-deploy
    prod: ''
  download_url:
    dev:
      url: ''
    prod:
      url: ''
  source_db:
    dev:
      host: ''
      user: ''
      p: ''
      db: ''
    prod:
      host: ''
      user: ''
      p: ''
      db: ''
    